- name: mongodb
  hosts: mongodb
  become: yes
  tasks:
    - name: Install MongoDB
      ansible.builtin.dnf:
        name: mongodb-org
        state: present

    - name: Copy MongoDB repo
      ansible.builtin.copy:
        src: mongo.repo
        dest: /etc/yum.repos.d/mongo.repo
        
    - name: Start and enable MongoDB service
      ansible.builtin.service:
        name: mongod
        state: started
        enabled: yes
